Занятие 1
js-tasks-ru/jsbasic-20210621_an-chendeva pull request #2
Opened 2021-07-01 22:24 UTC by anastasiagal

2021-07-01 22:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-02 14:00 UTC, SinimaWath requested changes

2021-07-02 14:00 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Давай попробуем этот сложный if упростить до одной строчки: `return name != null && ...` Чтобы было намного читаемей

2021-07-02 14:00 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    }
regExp.test(text) - eже возвращает true/false:
`return regExp.test(text)`

2021-07-02 14:00 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return str.slice(0,end) + "…"
Давай попробуем написать без временной переменной end, она тут ненмого излишне

2021-07-02 15:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-02 15:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-02 15:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-04 12:38 UTC, SinimaWath approved these changes

2021-07-04 12:39 UTC, merged