Занятие 2 + Занятие 3
js-tasks-ru/jsbasic-20210621_an-chendeva pull request #3
Opened 2021-07-12 18:18 UTC by anastasiagal

2021-07-12 18:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-13 13:18 UTC, SinimaWath requested changes
Давай уберем на всех задачах код для тестирования. Чтобы проверить, работает или нет используй npm test

2021-07-13 13:18 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  sum = 0;
Это неявное создание переменной, которое пишет в глобальный обьект на самом деле

Используй let.

2021-07-13 13:18 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    calculator["a"] = a
Для того, чтобы использовать свойства обьекта. Надо использовать this, на лекциях про обьекты и про функции, рассказывал почему

2021-07-13 13:18 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return num;
Давай используем спецальный метод filter, у массивов

2021-07-13 13:18 UTC, SinimaWath commented on 3-module/3-task/index.js
>  }
У тебя уже есть эта функция в другой задаче именно это и ломает тесты. Давай ее уберем или переименуем

2021-07-13 13:18 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
Давай используем более подходящий метод map

2021-07-13 13:18 UTC, SinimaWath commented on 3-module/4-task/index.js
>  }
Тут тоже `filter -> map`

2021-07-13 13:18 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  }
- Эту запись можно переписать на более понятную: `filter -> map`
- strarr[loopvar] * 1 - неочевидное приведение типов, используй parseInt

2021-07-16 21:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-17 19:30 UTC, SinimaWath requested changes

2021-07-17 19:30 UTC, SinimaWath commented on 2-module/2-task/index.js
> +isEmpty(obj);
Убери пожалуйста из всех задача код для тестирования. Именно из-за них падают тесты (

2021-07-17 19:30 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return users.filter(item => item["age"] <= age).map(item => item["name"] + ", " + item["balance"]).join('\n');
- Давай используем тут шаблонные строки, которые показывал на лекции.
- item["name"] - тут излишне, так как можно получить свойство через item.name, в других случаях также

2021-07-17 19:30 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  let arr = str.split(/,| /).filter(item => parseInt(item)).map(item => item * 1).sort((a, b) => a - b);
Это все таки должен быть const

2021-07-17 19:30 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Давай используем map, вместо  for in

2021-07-18 18:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-19 12:57 UTC, SinimaWath approved these changes

2021-07-19 12:58 UTC, merged